version: "3.8"
services:
    srs:
        #image: ossrs/srs:v4.0.136
        #image: 76527413/srs
        image: 76527413/srs:arm64
        environment:
            - CANDIDATE=*
        ports:
            - 1935:1935
            - 8080:8080
            - 1985:1985
            - 8000:8000/udp
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./conf:/usr/local/srs/conf
            - ./tmp/srs:/usr/local/srs/objs/nginx/html/live
    ffmpeg:
        image: jrottenberg/ffmpeg:4.1-ubuntu1804
        volumes:
            - ./test.mp4:/tmp/workdir/test.mp4
        command: -y -re -stream_loop -1 -i "test.mp4" -f flv -c copy -y "rtmp://srs/live/test"
        depends_on:
            - srs
    nginx:
        image: nginx:1.21.0
        ports:
            - 80:80
        volumes:
            - ./html:/usr/share/nginx/html
        depends_on: 
            - ffmpeg
